In [3]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
import numpy as np
#  Import and read the owid-covid-data.csv.
loc_df = pd.read_csv("locations.csv")
loc_df.head()

,location,iso_code,vaccines,last_observation_date,source_name
0,Afghanistan,AFG,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",8/31/2021,World Health Organization
1,Albania,ALB,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",9/12/2021,Ministry of Health
2,Algeria,DZA,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",9/12/2021,World Health Organization
3,Andorra,AND,"Oxford/AstraZeneca, Pfizer/BioNTech",8/29/2021,Government of Andorra
4,Angola,AGO,Oxford/AstraZeneca,9/11/2021,World Health Organization

In [4]:
# Drop the non-beneficial ID columns.
loc_df = loc_df.drop(['source_name','last_observation_date', 'iso_code'],axis = 1)
loc_df

              location                                           vaccines
0          Afghanistan  Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...
1              Albania  Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...
2              Algeria   Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V
3              Andorra                Oxford/AstraZeneca, Pfizer/BioNTech
4               Angola                                 Oxford/AstraZeneca
..                 ...                                                ...
217              Wales       Moderna, Oxford/AstraZeneca, Pfizer/BioNTech
218  Wallis and Futuna                                 Oxford/AstraZeneca
219              Yemen                Johnson&Johnson, Oxford/AstraZeneca
220             Zambia              Oxford/AstraZeneca, Sinopharm/Beijing
221           Zimbabwe  Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...

[222 rows x 2 columns]

In [6]:
new_df = pd.DataFrame(loc_df, columns = ['location'])

In [15]:
df = pd.DataFrame(
[{"Location": location,
  "J_and_J" : johnson,
  "AstraZeneca" : astrazeneca,
  "Pfizer" : pfizer,
  "Moderna" : moderna,
  "Sinopharm" : sinopharm,
  "Sputnik_V" : sputnik}])

NameError: name 'location' is not defined

NameError: name 'johnson' is not defined

In [3]:
loc_df.nunique()

location    222
vaccines     70
dtype: int64

In [4]:
loc_df.dtypes

location    object
vaccines    object
dtype: object

In [5]:
vax_df = pd.DataFrame(loc_df['vaccines'].str.split().values.tolist())

In [6]:
vax_df

,0,1,2,3,4,5,6,7,8
0,"Johnson&Johnson,","Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None,None
1,"Oxford/AstraZeneca,","Pfizer/BioNTech,","Sinovac,",Sputnik,V,None,None,None,None
2,"Oxford/AstraZeneca,","Sinopharm/Beijing,",Sputnik,V,None,None,None,None,None
3,"Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None,None
4,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
217,"Moderna,","Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None
218,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
219,"Johnson&Johnson,",Oxford/AstraZeneca,None,None,None,None,None,None,None
220,"Oxford/AstraZeneca,",Sinopharm/Beijing,None,None,None,None,None,None,None
221,"Oxford/AstraZeneca,","Sinopharm/Beijing,","Sinovac,",Sputnik,V,None,None,None,None

In [15]:
my_dict = {0: 'Vax 1', 1: 'Vax 2', 2: 'Vax 3',3: 'Vax 4',4: 'Vax 5',5: 'Vax 6',6: 'Vax 7',7: 'Vax 8',8: 'Vax 9'}
vax_df.rename(columns = my_dict, inplace = True)

In [16]:
vax_df

,Vax 1,Vax 2,Vax 3,Vax 4,Vax 5,Vax 6,Vax 7,Vax 8,Vax 9
0,"Johnson&Johnson,","Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None,None
1,"Oxford/AstraZeneca,","Pfizer/BioNTech,","Sinovac,",Sputnik,V,None,None,None,None
2,"Oxford/AstraZeneca,","Sinopharm/Beijing,",Sputnik,V,None,None,None,None,None
3,"Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None,None
4,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
217,"Moderna,","Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None
218,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
219,"Johnson&Johnson,",Oxford/AstraZeneca,None,None,None,None,None,None,None
220,"Oxford/AstraZeneca,",Sinopharm/Beijing,None,None,None,None,None,None,None
221,"Oxford/AstraZeneca,","Sinopharm/Beijing,","Sinovac,",Sputnik,V,None,None,None,None

In [17]:
# Drop the vaccination column from loc_df.
loc_df= loc_df.drop(['vaccines'],axis = 1)
loc_df.head()

      location
0  Afghanistan
1      Albania
2      Algeria
3      Andorra
4       Angola

In [18]:
vax_loc_df=pd.concat([loc_df, vax_df], axis=1)
vax_loc_df

,location,Vax 1,Vax 2,Vax 3,Vax 4,Vax 5,Vax 6,Vax 7,Vax 8,Vax 9
0,Afghanistan,"Johnson&Johnson,","Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None,None
1,Albania,"Oxford/AstraZeneca,","Pfizer/BioNTech,","Sinovac,",Sputnik,V,None,None,None,None
2,Algeria,"Oxford/AstraZeneca,","Sinopharm/Beijing,",Sputnik,V,None,None,None,None,None
3,Andorra,"Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None,None
4,Angola,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
217,Wales,"Moderna,","Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None
218,Wallis and Futuna,Oxford/AstraZeneca,None,None,None,None,None,None,None,None
219,Yemen,"Johnson&Johnson,",Oxford/AstraZeneca,None,None,None,None,None,None,None
220,Zambia,"Oxford/AstraZeneca,",Sinopharm/Beijing,None,None,None,None,None,None,None
221,Zimbabwe,"Oxford/AstraZeneca,","Sinopharm/Beijing,","Sinovac,",Sputnik,V,None,None,None,None

In [19]:
vax_loc_df.nunique()

location    222
Vax 1        18
Vax 2        17
Vax 3        14
Vax 4        11
Vax 5         7
Vax 6         4
Vax 7         3
Vax 8         2
Vax 9         1
dtype: int64

In [20]:
print(vax_loc_df.columns.tolist())

['location', 'Vax 1', 'Vax 2', 'Vax 3', 'Vax 4', 'Vax 5', 'Vax 6', 'Vax 7', 'Vax 8', 'Vax 9']

In [21]:
vax_loc_df=vax_loc_df.replace({'V': None})

In [22]:
vax_loc_df.nunique()

location    222
Vax 1        18
Vax 2        16
Vax 3        13
Vax 4        10
Vax 5         6
Vax 6         3
Vax 7         2
Vax 8         1
Vax 9         0
dtype: int64

In [23]:
# Drop the 8 column from vax_loc_df.
vax_loc_df.drop(vax_loc_df.columns[9],axis=1,inplace=True)

In [24]:
vax_loc_df.head(20)

,location,Vax 1,Vax 2,Vax 3,Vax 4,Vax 5,Vax 6,Vax 7,Vax 8
0,Afghanistan,"Johnson&Johnson,","Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None
1,Albania,"Oxford/AstraZeneca,","Pfizer/BioNTech,","Sinovac,",Sputnik,None,None,None,None
2,Algeria,"Oxford/AstraZeneca,","Sinopharm/Beijing,",Sputnik,None,None,None,None,None
3,Andorra,"Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None
4,Angola,Oxford/AstraZeneca,None,None,None,None,None,None,None
5,Anguilla,Oxford/AstraZeneca,None,None,None,None,None,None,None
6,Antigua and Barbuda,Oxford/AstraZeneca,None,None,None,None,None,None,None
7,Argentina,"CanSino,","Moderna,","Oxford/AstraZeneca,","Sinopharm/Beijing,",Sputnik,None,None,None
8,Armenia,"Oxford/AstraZeneca,","Sinovac,",Sputnik,None,None,None,None,None
9,Aruba,Pfizer/BioNTech,None,None,None,None,None,None,None
10,Australia,"Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None,None,None
11,Austria,"Johnson&Johnson,","Moderna,","Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None
12,Azerbaijan,"Oxford/AstraZeneca,","Sinovac,",Sputnik,None,None,None,None,None
13,Bahamas,Oxford/AstraZeneca,None,None,None,None,None,None,None
14,Bahrain,"Oxford/AstraZeneca,","Pfizer/BioNTech,","Sinopharm/Beijing,",Sputnik,None,None,None,None
15,Bangladesh,"Moderna,","Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None
16,Barbados,"Oxford/AstraZeneca,","Pfizer/BioNTech,",Sinopharm/Beijing,None,None,None,None,None
17,Belarus,"Sinopharm/Beijing,",Sputnik,None,None,None,None,None,None
18,Belgium,"Johnson&Johnson,","Moderna,","Oxford/AstraZeneca,",Pfizer/BioNTech,None,None,None,None
19,Belize,"Oxford/AstraZeneca,",Sinopharm/Beijing,None,None,None,None,None,None

In [25]:
vax_loc_df.replace(',','', regex=True, inplace=True)

In [26]:
vax_loc_df.head(20)

,location,Vax 1,Vax 2,Vax 3,Vax 4,Vax 5,Vax 6,Vax 7,Vax 8
0,Afghanistan,Johnson&Johnson,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
1,Albania,Oxford/AstraZeneca,Pfizer/BioNTech,Sinovac,Sputnik,None,None,None,None
2,Algeria,Oxford/AstraZeneca,Sinopharm/Beijing,Sputnik,None,None,None,None,None
3,Andorra,Oxford/AstraZeneca,Pfizer/BioNTech,None,None,None,None,None,None
4,Angola,Oxford/AstraZeneca,None,None,None,None,None,None,None
5,Anguilla,Oxford/AstraZeneca,None,None,None,None,None,None,None
6,Antigua and Barbuda,Oxford/AstraZeneca,None,None,None,None,None,None,None
7,Argentina,CanSino,Moderna,Oxford/AstraZeneca,Sinopharm/Beijing,Sputnik,None,None,None
8,Armenia,Oxford/AstraZeneca,Sinovac,Sputnik,None,None,None,None,None
9,Aruba,Pfizer/BioNTech,None,None,None,None,None,None,None
10,Australia,Oxford/AstraZeneca,Pfizer/BioNTech,None,None,None,None,None,None
11,Austria,Johnson&Johnson,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,None,None,None,None
12,Azerbaijan,Oxford/AstraZeneca,Sinovac,Sputnik,None,None,None,None,None
13,Bahamas,Oxford/AstraZeneca,None,None,None,None,None,None,None
14,Bahrain,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,Sputnik,None,None,None,None
15,Bangladesh,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None
16,Barbados,Oxford/AstraZeneca,Pfizer/BioNTech,Sinopharm/Beijing,None,None,None,None,None
17,Belarus,Sinopharm/Beijing,Sputnik,None,None,None,None,None,None
18,Belgium,Johnson&Johnson,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,None,None,None,None
19,Belize,Oxford/AstraZeneca,Sinopharm/Beijing,None,None,None,None,None,None

In [27]:
vax_loc_df.to_csv("vax_manuf_filtered.csv")