In [9]:
# Import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
import numpy as np
#  Import and read the owid-covid-data.csv.
vax_loc_df = pd.read_csv("Resources/csv files/locations.csv")
vax_loc_df.head()

,location,iso_code,vaccines,last_observation_date,source_name
0,Afghanistan,AFG,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",8/31/2021,World Health Organization
1,Albania,ALB,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",9/12/2021,Ministry of Health
2,Algeria,DZA,"Oxford/AstraZeneca, Sinopharm/Beijing, Sputnik V",9/12/2021,World Health Organization
3,Andorra,AND,"Oxford/AstraZeneca, Pfizer/BioNTech",8/29/2021,Government of Andorra
4,Angola,AGO,Oxford/AstraZeneca,9/11/2021,World Health Organization

In [10]:
# Drop the non-beneficial ID columns.
vax_loc_df = vax_loc_df.drop(['source_name','last_observation_date', 'iso_code','vaccines'],axis = 1)
vax_loc_df

              location
0          Afghanistan
1              Albania
2              Algeria
3              Andorra
4               Angola
..                 ...
217              Wales
218  Wallis and Futuna
219              Yemen
220             Zambia
221           Zimbabwe

[222 rows x 1 columns]

In [11]:
vax_loc_df.to_csv("loc_df.csv")

In [16]:
#  Import and read the owid-covid-data.csv.
vax_onehot_df = pd.read_csv("Resources/csv files/vax_loc_onehot.csv")
vax_onehot_df.head()

,Unnamed: 0,Abdala,COVIran Barekat,CanSino,Covaxin,EpiVacCorona,Johnson&Johnson,Medigen,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,QazVac,Sinopharm/Beijing,Sinopharm/HayatVax,Sinopharm/Wuhan,Sinovac,Soberana02,Sputnik V,ZF2001
0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0
2,2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
3,3,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [17]:
vax_onehot_df.drop('Unnamed: 0', axis=1, inplace=True)
vax_onehot_df.head()

,Abdala,COVIran Barekat,CanSino,Covaxin,EpiVacCorona,Johnson&Johnson,Medigen,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,QazVac,Sinopharm/Beijing,Sinopharm/HayatVax,Sinopharm/Wuhan,Sinovac,Soberana02,Sputnik V,ZF2001
0,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0
2,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [18]:
vax_loc_df=pd.concat([vax_loc_df, vax_onehot_df], axis=1)
vax_loc_df

,location,Abdala,COVIran Barekat,CanSino,Covaxin,EpiVacCorona,Johnson&Johnson,Medigen,Moderna,Oxford/AstraZeneca,Pfizer/BioNTech,QazVac,Sinopharm/Beijing,Sinopharm/HayatVax,Sinopharm/Wuhan,Sinovac,Soberana02,Sputnik V,ZF2001
0,Afghanistan,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0
1,Albania,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,1,0
2,Algeria,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
3,Andorra,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
4,Angola,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Wales,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0
218,Wallis and Futuna,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
219,Yemen,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0
220,Zambia,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
221,Zimbabwe,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0

In [19]:
vax_loc_df.nunique()

location              222
Abdala                  2
COVIran Barekat         2
CanSino                 2
Covaxin                 2
EpiVacCorona            2
Johnson&Johnson         2
Medigen                 2
Moderna                 2
Oxford/AstraZeneca      2
Pfizer/BioNTech         2
QazVac                  2
Sinopharm/Beijing       2
Sinopharm/HayatVax      2
Sinopharm/Wuhan         2
Sinovac                 2
Soberana02              2
Sputnik V               2
ZF2001                  2
dtype: int64

In [20]:
print(vax_loc_df.columns.tolist())

['location', 'Abdala', 'COVIran Barekat', 'CanSino', 'Covaxin', 'EpiVacCorona', 'Johnson&Johnson', 'Medigen', 'Moderna', 'Oxford/AstraZeneca', 'Pfizer/BioNTech', 'QazVac', 'Sinopharm/Beijing', 'Sinopharm/HayatVax', 'Sinopharm/Wuhan', 'Sinovac', 'Soberana02', 'Sputnik V', 'ZF2001']

In [30]:
vax_loc_df = vax_loc_df.rename(columns={"COVIran Barekat":"COVIran_Barekat","Johnson&Johnson":"Johnson_Johnson","Pfizer/BioNTech":"Pfizer_BioNTech", "Sinopharm/Beijing":'Sinopharm_Beijing', 'Sinopharm/HayatVax':'Sinopharm_HayatVax', 'Sinopharm/Wuhan':'Sinopharm_Wuhan', 'Sputnik V':'Sputnik_V',"Oxford/AstraZeneca":"Oxford_AstraZeneca"  })

,location,Abdala,COVIran_Barekat,CanSino,Covaxin,EpiVacCorona,Johnson_Johnson,Medigen,Moderna,Oxford_AstraZeneca,Pfizer_BioNTech,QazVac,Sinopharm_Beijing,Sinopharm_HayatVax,Sinopharm_Wuhan,Sinovac,Soberana02,Sputnik_V,ZF2001
0,Afghanistan,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0
2,Algeria,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0
3,Andorra,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
4,Angola,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5,Anguilla,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Wales,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0
218,Wallis and Futuna,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
219,Yemen,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0
220,Zambia,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
221,Zimbabwe,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,0

In [36]:
vax_loc_df.to_csv("Resources/csv files/vax_manuf_filtered.csv",index=False)